### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by tpfwrz** [OmgImAlexis/h#1]
Just wanted to suggest that https://github.com/caprover/caprover could be of use to you
its pretty amazing and ive been using it for docker deployments the last 2 years.
Found this repo from the https://github.com/Rush/link-module-alias/issues/3#issuecomment-453976562 issue of vscode iitellisense

While here did you ever find a solution to the issue(module-alias doesn't provide intellisense and link-module-alias deletes folders prefixed with @ :(   )

**Comment by OmgImAlexis** [comment]
I’ve tried caprover and didn’t like it personally. I plan on redoing this soon to add more functionality.

I ended up just using full paths again.
